language: node_js
node_js:
  - '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: Xl1cmE82Pmdkoz4SGPh4M6fHh0j2LSKs/6hjsD/N/TgtnFRtryHRbRctKxuAbHeuD7yK1+H+tiXh1RlUGKkVnRBh/tOtKmHvM61DLcd+SP9jS+W9ZdpyBUUATMl3PlP91BCFCG7lVWwMW2dYRqAG4Da3RNQuHfw0ZNF8mft5YPavpcdVua0gmPQRltLSXxDmfUoiOvG0Yl/FZdTeF3lTeywmWH4YP8hImiq3cjlQa+XOD7dustq/ihArJOrqUX19loMhrac7EUG+YaoL0iKnEiBlCJpJGxFW7WJMpJKKmVSszEZLmVPyhQrz1E1bCweWUd214eW37uvPDRxADNs2YrwHBCufPYYPOFcCEYfCQ1HsSBv50ATWg6ruj/qOcDGJsGhgO18B2t/dSVZJnSRxUYMHwgunTImZtoJh+5ZQOc9HA+lRGCw9i3N5VFFc0UsvfERH4qfB1+fuYlcCMsczSpsllFyd0qrj+K7c+uHqEMyQnYDMqzCixPcDekh/MXLWSTM/LNer7UxiU1JRogqLJs1hraB9YQr4RDnlKubjfsmmpXQ8nXdL58NMpYuWFYJsnlST53dwL6gvHPp1ofAmDUr0Ypn1pGnquSJXIf0Am8OmDWwEdpr3qKeUN9FT5iFuKwW6mtn/JcpnRtIKOnbliUoVsK4ylAgN/gIppuZoNGg=
  app: mozcurius
  skip_cleanup: true
  on:
    repo: marco-c/mercurius
    branch: master
env:
  global:
    - CXX=g++-4.8
    - REDISCLOUD_URL=redis://localhost:6379
before_script: redis-server /etc/redis/redis.conf --port 6379
