language: node_js
node_js:
- '0.12'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: sd1nsNL8RQNhVxna4KO5j/YIRseubRazeAnEsZTXqcZXSJ/l3+kA+/LBVuIjZYGpNp0sg3L5/M1KdcQ42MzT4PgSHvonCpLNntJxTNWZbT/JMgM3j99IMb4Tt+fOSqSu2pBZIQhUg75BS4ojpsEYP9mEzoW2uuTK8+JBFPt++vBEs1u/I9PULAjAbH7ZSk7QbjQv7vOYoLkTIGvcoMlV0Cj+/B8OH+Uee4+d7r79iiufWyclL7rzoXDwxHjd0UJIMCaQNmorA3+6mAivOc/S+fIYP9D1sjjDnw0hPl+m0WVkiqizjVCWK0t6AMghAUIDwkrBqo62Ur+w2DZBbUl1IUxgQKR8ZYLLXjngOWGM3YAOAVEyk77QZgsgw5VO8P2CgYi8MrsSGHUxd9dAkfa2e2wy38XFEudnK46NXurqgzjnIKAFqRGPVlnhXIsnkp/yZzFGZOhZusx+sh2+ZsrhjjsNXpm0FxQsLp1GGHIGuBSp9A9Iij1OrPY/k4qotGKUCdQmBNxwLWBWecvePeZqKHLS5VcvlQhvek54/kLobUhUFMgW2wmBiw7p1Z+J4qpaBWac6Q3FXSYuePkxIvEJsOfX+ynwq/VRbwP2/tikyjGkDxKrj2rf0s/2PfIQIhye3Hlr8hi/2FOF+IVRL7Cv/nrMS1JIGkNmKmnLU/6VLMc=
  app: mozcurius
  skip_cleanup: true
  on:
    repo: marco-c/mercurius
    branch: master
    node: '4'
env:
  REDISCLOUD_URL: redis://localhost:6379
before_script: redis-server /etc/redis/redis.conf --port 6379
