language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: kXOWQX+9k2/kpGFzACGpw/LGDIG6hybwj3v+ZnQ0zd1Us25U/vjyaHEtXlUHiqLJ2X/LRh0zf7YA+ARkh3KDAOx34YrF6fRjDLrlLks8Xom7JZ0NiKfNlNiOlSTF9SjwkDQj+rTA/HFoAAvvAi8iVyqIc4Lw2hmsvQWVIzBwUJVUHAUqC42s8nG1n9dIdnm5T2lwBXpvjBZBdMruzgf6HuoyPjJvLpQFYCcXsghlEC+cs5JaEoBeY1WBcgg3oqRcAt2qCrqaCoc1hkVcLGYeP7RDs+c22UVEO978UqVC7yKPClj4FkS8P6+hS+/Ef6nlIixjgeQuTT1WzANkBhgruN65syrSZJVFDgGgvdMP8iW+MdejjFUwSzzwZuk4U+ypgb76yM9PQhGWI76lJiOyT0aLqEX+z9mAYRzxPqgbV3v8OYdXU0qngGR1h05NjksTvJ7LiQnE6lngYWlNglo64UKmmspW6diy5J/udJodIYYZHSzw/NXZLQ4j0CtHK5mh78G7ewrqhpMmSTmjjT9a4uiyvg/WDC7o1ljOe/uSnKupHk1PNFE0VqKwN/HNXWCqzNWDJ0aSZfyBc5vqwN2tNKf/e/7cmZ3IM3dUXwYwergO08KpHeXiMx/omuPgUbqu0fqSttb5f+gi+Z1N9Z+bPUCEbdZcntGOcrVPUimyiT0=
  app: mozcurius
  skip_cleanup: true
  on:
    repo: marco-c/mercurius
    branch: master
env:
  REDISCLOUD_URL: redis://localhost:6379
before_script: redis-server /etc/redis/redis.conf --port 6379
