language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: n9PrIRLUMbIWJJVmi6QEEDLEiFAUbBS+3PDIJSvoNUFNGip8YBSHjY0DNPPTbetXNu1BWUb5L6ZIjig8kF31sAh8FvjX5YcndRPkxzoJ9g0RtvsV42kx8kK2WXClOp6lzlNVTidhPhbK+HMbfzOBUmkRXyL178NC+6u5RcTVgCtCQUPLuTReXmeBeK8A2TtPY9wwLvsO7KzHe6M41BJ31f5XTU2wTdUp3aEb0MFwayC1JnVSDVVk5XmZFkJpR46sYINlHJmcRYBiF3BWbAkw156SKg6jUV39xGnx7KL9wOrA69sMnJZl8afPC+34GHLsf2YrZxQl/owVh/BQK2dvMQgtD3tzPMdoFGW/isxqi2MCD+0ejxbKVbtHoXprHEeP2nGGJ4xL+JPhuaZffyIFR7ti02m74OGiwnvm/+NubWPaoH75dqhK8FMYrr77p5zfIDK2RqQeHWIV/8b+7uC90u2Lm07wksmOm7MeO7sOQfmPQToau28oXmQouR/Jsjrgk0peji04IeTOuxoEqnKBk0Qd63gVXz/V2c8p1g0O3ZdQ5Cwft7OZx5zUTzyd7GXkuncKKqdt1FCP64Qub61tqYbnesffh3qKJ+RpgQh1vlfK/t2eBUHMtk9OOZ+u009W0fuxN3q+U0/+HG1weMd4msKoKMsEsdaARnb/4jMaUw4=
  app: mozcurius
  skip_cleanup: true
  on:
    repo: marco-c/mercurius
    branch: master
env:
  REDISCLOUD_URL: redis://localhost:6379
before_script: redis-server /etc/redis/redis.conf --port 6379
