language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: UQkyP3jHgCyDN0OGBb10LCD64xwoCXSS0V/i6p95aj8IBTq9tyH6ggfviO6FiQvZD/KDIsI0Aoym7nCTJoNRIUxmx5zqLDjt9upE8MCcvfQZvQ/Omi0O22ERjI+sb17I4WvfSUM7Vy5vHHOesPX2n+tm3JapTl6yflkNPCPR5JFT9+NfmusHChVNiEV+6VPyMfApA8vtPysyp1jaSEwrgtgrTUAfTcO4LRIDPj/VHJInSma/5X2zQWpNbVFarPGoPdEyy0HZ+UWZxwEpkjK5NzZojIIMe/0/pXMih9WIJLNaysbfR7Lpu9Kl+HJ87Ih9LazDAhYMPl3R2khSiOseMr5kspMw/28xmsQ54tzoaGqcaQLsX6diI6HsNH8SH0xnI8q5Dube4qexkmcMrdc+9zpYzzIDLA9RMyKXHdf7QsaC0pTYqdtF5+mq69P+tQ+SIHMy0JdXYCxmTtcVQqZ4/xVuxGJ5kc+vxYtMsgcB6ouYXDbiptge9Vv0ImX1fRKGFYRnCGHzuSguFk1ff41W+Zw105FcU6tFLKitg+vAfHP4rdvet8SDFYpZW7+TxFU+F1/zABT9zhSrsrYXkvMoC4VAUYTdKn+kQXeq8GjgR3k8UkBKQKhsWRKXJL4bZBq2KDBaPwjlDB1WntUa+SJbW7Esf4fftunebzsD15kXHO8=
  app: mozcurius
  skip_cleanup: true
  on:
    repo: marco-c/mercurius
    branch: master
env:
  REDISCLOUD_URL: redis://localhost:6379
before_script: redis-server /etc/redis/redis.conf --port 6379
